### ISSUE TITLE
Benchmark feladatok

### ISSUE THREAD

**Issue by piller-imre** [davida326/Szakdolgozat#6]
Összegyűjteni néhány feladatot, amit érdemes lehet majd mérni (pl. Phoronix alapján)

**Comment by davida326** [comment]
Phoronix Test Suite v9.8.0
4 Tests Installed

pts/apache-1.7.2           - Apache Benchmark                                (System)       
pts/build-linux-kernel-1.10.2 - Timed Linux Kernel Compilation     (Processor)
pts/openarena-1.5.5        - OpenArena                                           (Graphics)
pts/sqlite-2.1.0           - SQLite                                                        (Disk)

Ezekből megpróbálom az apache benchmark-ot vizsgálni/mérni, más prioritási szinteken, illetve más ütemezővel
